import pandas_ta as ta

MyStrategy = ta.Strategy(
        name="DCSMA10",
        ta=[
            {"kind": "sma", "length": 10},
            {"kind": "sma", "length": 10},
            {"kind": "sma", "length": 20},
            {"kind": "sma", "length": 20},
            {"kind": "sma", "length": 50},
            {"kind": "sma", "length": 100},
            {"kind": "sma", "length": 200},
            {"kind": "ema", "length": 10},
            {"kind": "ema", "length": 20},
            {"kind": "ema", "length": 20},
            {"kind": "ema", "length": 50},
            {"kind": "ema", "length": 100},
            {"kind": "ema", "length": 200},
            {"kind": "macd", "fast": 12, "slow": 26, "signal": 9},
            {"kind": "rsi", "length": 14, "scalar": 100},
            {"kind": "bbands"},
            {"kind": "kc"},
            {"kind": "obv"},
            {"kind": "ad"},
            {"kind": "stoch"},
            {"kind": "stochrsi"},
        ]
    )

stock_list = ['AESB3', 'AGRO3', 'ALLD3', 'ALPK3', 'ALUP11', 'AMBP3', 'AMER3',
       'ARZZ3', 'AZEV4', 'AZUL4', 'B3SA3', 'BEEF3', 'BPAC11', 'BPAN4',
       'BRAP4', 'BRBI11', 'BRIT3', 'BRKM5', 'BRPR3', 'BRSR6', 'CASH3',
       'CBAV3', 'CGRA4', 'CLSA3', 'CMIN3', 'COGN3', 'CSAN3', 'CSED3',
       'CURY3', 'CVCB3', 'DESK3', 'DIRR3', 'DOTZ3', 'ECOR3', 'ELET6',
       'EMBR3', 'ENEV3', 'ENJU3', 'ESPA3', 'EVEN3', 'EZTC3', 'FIQE3',
       'G2DI33', 'GGBR4', 'GGPS3', 'GMAT3', 'GUAR3', 'HBSA3', 'HYPE3',
       'INTB3', 'IRBR3', 'ITSA4', 'JALL3', 'JBSS3', 'KEPL3', 'KLBN11',
       'KRSA3', 'LAVV3', 'LIGT3', 'LJQQ3', 'LOGG3', 'LREN3', 'LWSA3',
       'MATD3', 'MDIA3', 'MELK3', 'MGLU3', 'MILS3', 'MLAS3', 'MOVI3',
       'MRFG3', 'MRVE3', 'MTRE3', 'MULT3', 'MYPK3', 'NEOE3', 'NINJ3',
       'NTCO3', 'OIBR3', 'ONCO3', 'ORVR3', 'PCAR3', 'PETR4', 'PETZ3',
       'PGMN3', 'PLPL3', 'PNVL3', 'PRIO3', 'PRNR3', 'PTNT4', 'RAIL3',
       'RANI3', 'RAPT4', 'RDOR3', 'RECV3', 'RRRP3', 'SBFG3', 'SCAR3',
       'SEER3', 'SEQL3', 'SHUL4', 'SIMH3', 'SMFT3', 'SOMA3', 'SYNE3',
       'TEND3', 'TFCO4', 'TPIS3', 'TRIS3', 'TTEN3', 'VALE3', 'VIVT3',
       'VULC3', 'WEST3', 'WIZC3', 'YDUQ3', 'ZAMP3']

companies = {'AESB3.SA': ['AES Brasil Energia SA', 'AESB3'],
 'AGRO3.SA': ['BrasilAgro', 'AGRO3'],
 'ALLD3.SA': ['Allied Tecnologia SA', 'ALLD3'],
 'ALPK3.SA': ['Alper Consultoria e Corretora de Seguros SA', 'ALPK3'],
 'ALUP11.SA': ['Alupar Investimento SA', 'ALUP11'],
 'AMBP3.SA': ['Ambipar', 'AMBP3'],
 'AMER3.SA': ['Americanas', 'AMER3'],
 'ARZZ3.SA': ['Arezzo Indústria e Comércio SA', 'ARZZ3'],
 'AZEV4.SA': ['Azevedo & Travassos SA', 'AZEV4'],
 'AZUL4.SA': ['Azul SA', 'AZUL4'],
 'B3SA3.SA': ['B3 SA - Brasil, Bolsa, Balcão', 'B3SA3'],
 'BEEF3.SA': ['Minerva SA', 'BEEF3'],
 'BPAC11.SA': ['BTG Pactual Participations', 'BPAC11'],
 'BPAN4.SA': ['Banco PAN SA', 'BPAN4'],
 'BRAP4.SA': ['BRADESPAR SA', 'BRAP4'],
 'BRBI11.SA': ['BRB Banco de Brasília SA', 'BRBI11'],
 'BRIT3.SA': ['Brisanet Participações SA', 'BRIT3'],
 'BRKM5.SA': ['Braskem SA', 'BRKM5'],
 'BRPR3.SA': ['BR Properties SA', 'BRPR3'],
 'BRSR6.SA': ['Banrisul SA', 'BRSR6'],
 'CASH3.SA': ['Méliuz SA', 'CASH3'],
 'CBAV3.SA': ['CBA - Companhia Brasileira de Alumínio', 'CBAV3'],
 'CGRA4.SA': ['Grazziotin SA', 'CGRA4'],
 'CLSA3.SA': ['ClearSale SA', 'CLSA3'],
 'CMIN3.SA': ['CSN Mineração SA', 'CMIN3'],
 'COGN3.SA': ['Cogna Educação SA', 'COGN3'],
 'CSAN3.SA': ['Cosan SA', 'CSAN3'],
 'CSED3.SA': ['Cruzeiro do Sul Educacional SA', 'CSED3'],
 'CURY3.SA': ['Cury Construtora e Incorporadora SA', 'CURY3'],
 'CVCB3.SA': ['CVC Brasil Operadora e Agência de Viagens SA', 'CVCB3'],
 'DESK3.SA': ['Desktop - Sigmanet SA', 'DESK3'],
 'DIRR3.SA': ['Direcional Engenharia SA', 'DIRR3'],
 'DOTZ3.SA': ['Dotz SA', 'DOTZ3'],
 'ECOR3.SA': ['EcoRodovias Infraestrutura e Logística SA', 'ECOR3'],
 'ELET6.SA': ['Centrais Elétricas Brasileiras SA', 'ELET6'],
 'EMBR3.SA': ['Embraer SA', 'EMBR3'],
 'ENEV3.SA': ['Eneva SA', 'ENEV3'],
 'ENJU3.SA': ['Enjoei SA', 'ENJU3'],
 'ESPA3.SA': ['MPM Corpóreos SA (EspaçoLaser)', 'ESPA3'],
 'EVEN3.SA': ['Even Construtora e Incorporadora SA', 'EVEN3'],
 'EZTC3.SA': ['EZTEC Empreendimentos e Participações SA', 'EZTC3'],
 'FIQE3.SA': ['UNIFIQUE TELECOMUNICAÇÕES S.A.', 'FIQE3'],
 'G2DI33.SA': ['G2D Investments', 'G2DI33'],
 'GGBR4.SA': ['Gerdau SA', 'GGBR4'],
 'GGPS3.SA': ['GPS Participações e Empreendimentos SA', 'GGPS3'],
 'GMAT3.SA': ['Grupo Mateus SA', 'GMAT3'],
 'GUAR3.SA': ['Guararapes Confecções SA', 'GUAR3'],
 'HBSA3.SA': ['Hidrovias do Brasil SA', 'HBSA3'],
 'HYPE3.SA': ['Hypera SA', 'HYPE3'],
 'INTB3.SA': ['Intelbras SA', 'INTB3'],
 'IRBR3.SA': ['IRB Brasil Resseguros SA', 'IRBR3'],
 'ITSA4.SA': ['Itaúsa SA', 'ITSA4'],
 'JALL3.SA': ['Jalles Machado SA', 'JALL3'],
 'JBSS3.SA': ['JBS SA', 'JBSS3'],
 'KEPL3.SA': ['Kepler Weber SA', 'KEPL3'],
 'KLBN11.SA': ['Klabin SA', 'KLBN11'],
 'KRSA3.SA': ['Kora Saúde Participações SA', 'KRSA3'],
 'LAVV3.SA': ['Lavvi Empreendimentos Imobiliários SA', 'LAVV3'],
 'LIGT3.SA': ['Light SA', 'LIGT3'],
 'LJQQ3.SA': ['Lojas Quero-Quero SA', 'LJQQ3'],
 'LOGG3.SA': ['Log Commercial Properties e Participações SA', 'LOGG3'],
 'LREN3.SA': ['Lojas Renner SA', 'LREN3'],
 'LWSA3.SA': ['Linx SA', 'LWSA3'],
 'MATD3.SA': ['Maternidade SA', 'MATD3'],
 'MDIA3.SA': ['M. Dias Branco SA Indústria e Comércio de Alimentos', 'MDIA3'],
 'MELK3.SA': ['Melhoramentos Papéis SA', 'MELK3'],
 'MGLU3.SA': ['Magazine Luiza SA', 'MGLU3'],
 'MILS3.SA': ['Mills Estruturas e Serviços de Engenharia SA', 'MILS3'],
 'MLAS3.SA': ['Moura Dubeux Engenharia SA', 'MLAS3'],
 'MOVI3.SA': ['Movida Participações SA', 'MOVI3'],
 'MRFG3.SA': ['Marfrig Global Foods SA', 'MRFG3'],
 'MRVE3.SA': ['MRV Engenharia e Participações SA', 'MRVE3'],
 'MTRE3.SA': ['Mitre Realty Empreendimentos e Participações SA', 'MTRE3'],
 'MULT3.SA': ['Multiplan Empreendimentos Imobiliários SA', 'MULT3'],
 'MYPK3.SA': ['Iochpe-Maxion SA', 'MYPK3'],
 'NEOE3.SA': ['Neoenergia SA', 'NEOE3'],
 'NINJ3.SA': ['Getninjas SA', 'NINJ3'],
 'NTCO3.SA': ['Natura & Co Holding SA', 'NTCO3'],
 'OIBR3.SA': ['Oi SA', 'OIBR3'],
 'ONCO3.SA': ['Oncoclínicas do Brasil Serviços Médicos SA', 'ONCO3'],
 'ORVR3.SA': ['Orizon Valorização de Resíduos SA', 'ORVR3'],
 'PCAR3.SA': ['Companhia Brasileira de Distribuição (Grupo Pão de Açúcar)',
  'PCAR3'],
 'PETR4.SA': ['Petrobras', 'PETR4'],
 'PETZ3.SA': ['Pet Center Comércio e Participações SA (Petz)', 'PETZ3'],
 'PGMN3.SA': ['Pague Menos SA', 'PGMN3'],
 'PLPL3.SA': ['Plano & Plano Desenvolvimento Imblr SA', 'PLPL3'],
 'PNVL3.SA': ['Dimed SA Distribuidora de Medicamentos', 'PNVL3'],
 'PRIO3.SA': ['PetroRio SA', 'PRIO3'],
 'PRNR3.SA': ['Priner Serviços Industriais SA', 'PRNR3'],
 'PTNT4.SA': ['Petenatti Industrial SA', 'PTNT4'],
 'RAIL3.SA': ['Rumo SA', 'RAIL3'],
 'RANI3.SA': ['Randon Implementos e Participações SA', 'RANI3'],
 'RAPT4.SA': ['Randon Participações SA', 'RAPT4'],
 'RDOR3.SA': ['Rede DOr São Luiz SA', 'RDOR3'],
 'RECV3.SA': ['Recrusul SA', 'RECV3'],
 'RRRP3.SA': ['3R Petroleum Óleo e Gás SA', 'RRRP3'],
 'SBFG3.SA': ['Grupo SBF SA', 'SBFG3'],
 'SCAR3.SA': ['Sincorá Indústria de Calçados SA', 'SCAR3'],
 'SEER3.SA': ['Ser Educacional SA', 'SEER3'],
 'SEQL3.SA': ['Sequoia Logística e Transporte SA', 'SEQL3'],
 'SHUL4.SA': ['Schulz SA', 'SHUL4'],
 'SIMH3.SA': ['Simpar SA', 'SIMH3'],
 'SMFT3.SA': ['Smartfit Escola de Ginástica e Dança SA', 'SMFT3'],
 'SOMA3.SA': ['Grupo de Moda SOMA SA', 'SOMA3'],
 'SYNE3.SA': ['Sinqia SA', 'SYNE3'],
 'TEND3.SA': ['Construtora Tenda SA', 'TEND3'],
 'TFCO4.SA': ['Track & Field Co SA', 'TFCO4'],
 'TPIS3.SA': ['Triunfo Participações e Investimentos SA', 'TPIS3'],
 'TRIS3.SA': ['Trisul SA', 'TRIS3'],
 'TTEN3.SA': ['Tenda Atacado SA', 'TTEN3'],
 'VALE3.SA': ['Vale SA', 'VALE3'],
 'VIVT3.SA': ['Telefônica Brasil SA', 'VIVT3'],
 'VULC3.SA': ['Vulcabras Azaleia SA', 'VULC3'],
 'WEST3.SA': ['Westwing Comércio Varejista SA', 'WEST3'],
 'WIZC3.SA': ['Wiz Soluções e Corretagem de Seguros SA', 'WIZC3'],
 'YDUQ3.SA': ['YDUQS Participações SA', 'YDUQ3'],
 'ZAMP3.SA': ['Zamp SA', 'ZAMP3'],
'^BVSP': ['Ibovespa','Ibovespa']
}